clean: true
author: "Alexis Aubry Radanovic"
author_url: https://github.com/alexaubry
github_url: https://github.com/alexaubry/HTMLString
github_file_prefix: https://github.com/alexaubry/HTMLString/tree/2.1.2
module_version: 2.1.2
xcodebuild_arguments: 
- -scheme
- HTMLString
- -destination
- 'platform=OS X,arch=x86_64'
module: HTMLString
root_url: https://alexaubry.github.io/HTMLString
output: docs/
swift_version: 3.0.2
copyright: "Copyright © 2016-2017 Alexis Aubry Radanovic. Licensed under the [MIT License](https://github.com/alexaubry/HTMLString/blob/master/LICENSE)."
skip_undocumented: true
theme: apple